<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-Content-English/blob/ankit%2FNumpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Creating an array in Numpy



In [ ]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.ndim)


<class 'numpy.ndarray'>
1


Numpy array is Homogeneous

In [ ]:

arr = np.array([1,2,3,4,5,6.6])
arr.dtype

dtype('float64')

Conversion int to uint8 for Saving Memory

In [ ]:

arr.dtype
arr = np.array([1,2,3,4,5],dtype="uint8")




**Time Complexity in Numpy**

In [ ]:
arr = np.array([1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1])
print(arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
%timeit sum(arr)

10000 loops, best of 5: 32 µs per loop


In [ ]:
%timeit arr.sum()

The slowest run took 35.16 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.39 µs per loop


Important Function to Create Numpy Array

In [46]:
arr = [1]*5

In [ ]:
arr = np.ones(5)  #creating array of 5 size with ones 
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
arr = np.zeros(3,dtype="int8")  
print(arr)

[0 0 0]


In [ ]:
arr = np.arange(2,10,2) #arange function 
print(arr)    

In [ ]:
arr = np.linspace(1,10,50)  #linspace
print(arr)

In [ ]:
arr = np.random.randn(100)
print(arr)

In [30]:
print(arr.mean(),arr.std())

-0.004647630559591394 0.984123676262071


In [ ]:
np.random.permutation(arr)

**2-D array**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

print(arr[0][1]) #accessing at specific index
print(arr[0,1])  #different method

In [38]:
arr = np.array([[1,2,3],[4,5,6]])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

**Slicing**

In [ ]:
arr = np.arange(5,25,2)  #created a arr
print(arr)


srr=arr[2:5]

print(srr)

[ 5  7  9 11 13 15 17 19 21 23]
[ 9 11 13]


In [ ]:

lst = [1,2,3,4,5]  #simple python array
lst2 = lst[2:4]  #slicing
print(lst)
print(lst2)
lst2[0] = 1000      #replacing value at index
print(lst)
print(lst2)



[1, 2, 3, 4, 5]
[3, 4]
[1, 2, 3, 4, 5]
[1000, 4]


In [ ]:
#slicing in 2-D array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


In [ ]:
srr=arr[0:1,1:3]
print(srr)

[[2 3]]


In [ ]:
arr[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Shallow Copy and Deep Copy**

In [ ]:
lst = np.array([1,2,3,4,5])  #numpy array
lst2 = lst[2:4]  #shallow copy
print(lst)
print(lst2)
lst2[0] = 1000      #replacing value at index
print(lst)
print(lst2)


[1 2 3 4 5]
[3 4]
[   1    2 1000    4    5]
[1000    4]


In [ ]:
lst = np.array([1,2,3,4,5])  #numpy array
lst2 = lst[2:4].copy()  #Deep copy
print(lst)
print(lst2)
lst2[0] = 1000      #replacing value at index
print(lst)
print(lst2)


[1 2 3 4 5]
[3 4]
[1 2 3 4 5]
[1000    4]


BroadCasting

In [34]:
a = np.array([ 1,  2, 34,  4,  5])
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[ 3  4 36  6  7]
[-1  0 32  2  3]
[ 2  4 68  8 10]
[ 0.5  1.  17.   2.   2.5]


In [35]:
print(a>3)
print(a>=3)
print(a<=4)
print(a<2)

[False False  True  True  True]
[False False  True  True  True]
[ True  True False  True False]
[ True False False False False]


Fancy Indexing

In [39]:
arr = np.array([1,2,3,4,5,6,7,8])

In [41]:
idxArr = [1,4,6]
arr[idxArr]

array([2, 5, 7])

In [42]:
arr[[True,False,True,True,True,False,True,True]]

array([1, 3, 4, 5, 7, 8])

In [43]:
arr<=4


array([ True,  True,  True,  True, False, False, False, False])

In [44]:
arr[(arr>=2)&(arr<=5)]

array([2, 3, 4, 5])

Some Important Function in Numpy

In [57]:
np.cos(arr)

array([0.54030231, 0.54030231, 0.54030231, 0.54030231, 0.54030231])

In [58]:
np.sin(arr)

array([0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098])

In [59]:
np.where(arr,100,45)

array([100, 100, 100, 100, 100])